##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="schema_registry" \
    CONTECO_NAME="base" \
    CONTECO_TAG="6.0.0" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="schema_registry" \
      io.vcweb.name="base" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="schema_registry.base - ContEco" \
      io.vcweb.description="Confluent Schema Registry base image, with configuration changes." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.schema_registry.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
