##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.schema-registry:5.3.1 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/etc/confluent/docker/run"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="schema-registry" \
    CONTECO_NAME="base" \
    CONTECO_TAG="5.3.1" \
    CONTECO_BASE="external.schema-registry:5.3.1" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="schema-registry" \
      io.vcweb.name="base" \
      io.vcweb.tag="5.3.1" \
      io.vcweb.base="external.schema-registry:5.3.1" \
      io.vcweb.build="image-base" \
      io.vcweb.label="schema-registry.base - ContEco" \
      io.vcweb.description="Confluent Schema Registry base image, with configuration changes." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.schema-registry.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
