#!/usr/bin/env bash

export CONTECO_LABEL="schema_registry.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Schema Registry base image, with configuration changes."

export CONTECO_TYPE="schema_registry"
export CONTECO_NAME="base"
export CONTECO_TAG="6.0.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/cp-schema-registry:6.0.0"
